[tool.tarpaulin]
# Output formats
out = ["Xml", "Html"]
output-dir = "coverage"

# Include all source files
include = ["src/**/*.rs"]

# Exclude test files and generated code
exclude = [
  "src/generated/**/*",
  "tests/**/*",
]

# Coverage settings
branch = true
line = true

# Timeout and other settings
run-types = ["Tests"]
timeout = 120
verbose = true

# Don't count doctest coverage
no-doc-tests = true
