name: CI

permissions:
  contents: read

on:
  push:
    branches: [master, development]
  pull_request:
    branches: [master, development]


env:
  CARGO_TERM_COLOR: always
  PYO3_CONFIGURE_OPS: "1"

jobs:
  # Test without LLVM first - this should always work
  test-no-llvm:
    name: Test without LLVM
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"

      - name: Install npm dependencies
        run: npm ci

      - name: Build Rust compiler (no LLVM)
        run: cd compiler && cargo build --no-default-features --verbose

      - name: Run Rust tests (no LLVM)
        run: cd compiler && cargo test --no-default-features --verbose

      - name: Run TypeScript tests
        run: npm test

  # Only test LLVM on Ubuntu where we know it might work
  test-with-llvm-ubuntu:
    name: Test with LLVM (Ubuntu only)
    runs-on: ubuntu-22.04
    needs: test-no-llvm # Only run if no-LLVM tests pass

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Try LLVM 14 installation
        run: |
          sudo apt-get update
          sudo apt-get install -y llvm-14 llvm-14-dev clang-14 libclang-14-dev
          echo "LLVM_SYS_140_PREFIX=/usr/lib/llvm-14" >> $GITHUB_ENV

          # Verify it worked
          if /usr/bin/llvm-config-14 --version; then
            echo "LLVM installation successful"
          else
            echo "LLVM installation failed, but that's okay"
            exit 0
          fi

      - name: Try building with LLVM
        run: |
          cd compiler
          if cargo build --verbose; then
            echo "✅ LLVM build successful!"
            cargo test --verbose
          else
            echo "❌ LLVM build failed, but non-LLVM builds work"
            exit 0
          fi

  # Code coverage job
  coverage:
    name: Code Coverage
    runs-on: ubuntu-22.04
    needs: test-no-llvm

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ~/.cargo/bin
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}-tarpaulin

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"

      - name: Install npm dependencies
        run: npm ci

      - name: Build TypeScript
        run: npm run build

      - name: Install cargo-tarpaulin
        run: |
          if ! command -v cargo-tarpaulin &> /dev/null; then
            cargo install cargo-tarpaulin
          else
            echo "cargo-tarpaulin already installed"
          fi

      - name: Generate TypeScript coverage
        run: npm run test:design:coverage

      - name: Generate Rust coverage
        run: npm run coverage:rust

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: ./coverage/coverage-final.json,./coverage/cobertura.xml
          fail_ci_if_error: false
          verbose: true
