name: CI

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]

env:
  CARGO_TERM_COLOR: always
  # Global LLVM environment variables
  LLVM_SYS_150_PREFIX: /usr/lib/llvm-15
  LLVM_CONFIG_PATH: /usr/bin/llvm-config-15

jobs:
  # Single Ubuntu job for cost efficiency
  test:
    name: Test (Ubuntu Only)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install LLVM
        run: |
          # Update package list and install LLVM dependencies
          sudo apt-get update -y

          # Install LLVM 15 with all necessary components
          sudo apt-get install -y \
            llvm-15 \
            llvm-15-dev \
            llvm-15-tools \
            llvm-15-runtime \
            libpolly-15-dev \
            clang-15 \
            libclang-15-dev \
            libc++-15-dev \
            libc++abi-15-dev \
            cmake \
            pkg-config \
            build-essential \
            zlib1g-dev \
            libzstd-dev \
            libffi-dev \
            libxml2-dev \
            libedit-dev

          # Verify critical files exist
          echo "Checking LLVM installation..."
          test -f /usr/bin/llvm-config-15 || (echo "llvm-config-15 not found" && exit 1)
          test -d /usr/lib/llvm-15/lib || (echo "LLVM lib directory not found" && exit 1)
          test -f /usr/lib/llvm-15/lib/libLLVM-15.so.1 || (echo "LLVM shared library not found" && exit 1)

          # Check for static libraries that llvm-sys might need
          echo "Checking for static libraries..."
          find /usr/lib/llvm-15/lib -name "*.a" | head -5 || true

      - name: Setup LLVM environment
        run: |
          # Set environment variables for LLVM
          echo "LLVM_SYS_150_PREFIX=/usr/lib/llvm-15" >> $GITHUB_ENV
          echo "LLVM_CONFIG_PATH=/usr/bin/llvm-config-15" >> $GITHUB_ENV
          echo "CC=clang-15" >> $GITHUB_ENV
          echo "CXX=clang++-15" >> $GITHUB_ENV

          # Additional environment variables that llvm-sys build script looks for
          echo "LLVM_CONFIG=/usr/bin/llvm-config-15" >> $GITHUB_ENV

          # Library path for linking
          echo "LD_LIBRARY_PATH=/usr/lib/llvm-15/lib:$LD_LIBRARY_PATH" >> $GITHUB_ENV
          echo "PKG_CONFIG_PATH=/usr/lib/llvm-15/lib/pkgconfig:$PKG_CONFIG_PATH" >> $GITHUB_ENV

          # Critical: Add library directory to system paths
          echo "LIBRARY_PATH=/usr/lib/llvm-15/lib:$LIBRARY_PATH" >> $GITHUB_ENV
          echo "CPATH=/usr/lib/llvm-15/include:$CPATH" >> $GITHUB_ENV

          # Set specific linker flags that llvm-sys needs
          echo "RUSTFLAGS=-L native=/usr/lib/llvm-15/lib -C link-arg=-Wl,-rpath,/usr/lib/llvm-15/lib" >> $GITHUB_ENV

          # Verify LLVM installation
          echo "Verifying LLVM installation..."
          /usr/bin/llvm-config-15 --version
          /usr/bin/llvm-config-15 --libdir
          /usr/bin/llvm-config-15 --includedir
          echo "Available LLVM libraries:"
          ls -la /usr/lib/llvm-15/lib/ | grep -E "\\.so|\\.a" | head -10

          # Create symbolic links for common library names
          sudo ln -sf /usr/bin/llvm-config-15 /usr/bin/llvm-config || true

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
        env:
          LLVM_SYS_150_PREFIX: /usr/lib/llvm-15
          LLVM_CONFIG_PATH: /usr/bin/llvm-config-15

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target/
            compiler/target/
          key: ${{ runner.os }}-cargo-llvm15-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-llvm15-
            ${{ runner.os }}-cargo-

      - name: Check Rust linting
        working-directory: compiler
        env:
          RUST_BACKTRACE: 1
        run: |
          echo "=== Environment Debug ==="
          echo "LLVM environment variables:"
          env | grep LLVM || true
          echo "Checking for llvm-config:"
          which llvm-config-15 || true
          llvm-config-15 --version || true
          llvm-config-15 --libs || true

          echo "=== Library Check ==="
          echo "LLVM library directory contents:"
          ls -la /usr/lib/llvm-15/lib/ | head -10

          echo "=== PKG Config Check ==="
          pkg-config --exists llvm-15 && echo "llvm-15 pkg-config found" || echo "llvm-15 pkg-config not found"

          echo "=== Running Clippy ==="
          cargo clippy -- -D warnings

      - name: Run Rust tests
        working-directory: compiler
        env:
          RUST_BACKTRACE: 1
          # Additional environment variables for build
          LLVM_SYS_150_PREFIX: /usr/lib/llvm-15
          LLVM_CONFIG_PATH: /usr/bin/llvm-config-15
          LLVM_CONFIG: /usr/bin/llvm-config-15
          LD_LIBRARY_PATH: /usr/lib/llvm-15/lib
          PKG_CONFIG_PATH: /usr/lib/llvm-15/lib/pkgconfig
        run: |
          echo "=== Pre-test Environment Check ==="
          env | grep -E "(LLVM|RUST)" || true
          echo "=== Running Tests ==="
          cargo test --verbose

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install npm dependencies
        run: npm ci

      - name: Run TypeScript tests
        run: npm run test:design
