name: Coverage

permissions:
  contents: read

on:
  push:
    branches: [master, development]
  pull_request:
    branches: [master, development]

jobs:
  coverage:
    name: Code Coverage
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ~/.cargo/bin
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}-tarpaulin

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"

      - name: Install npm dependencies
        run: npm ci

      - name: Build TypeScript
        run: npm run build

      - name: Install cargo-tarpaulin
        run: |
          if ! command -v cargo-tarpaulin &> /dev/null; then
            cargo install cargo-tarpaulin
          else
            echo "cargo-tarpaulin already installed"
          fi

      - name: Generate TypeScript coverage
        run: npm run test:design:coverage

      - name: Generate Rust coverage
        run: cd compiler && cargo tarpaulin --out Xml --output-dir ../coverage --output-files cobertura.xml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: cyl-lang/cyl
          files: ./coverage/lcov.info,./coverage/cobertura.xml
