name: Code Coverage

permissions:
  contents: read

on:
  push:
    branches: [master, development]
  pull_request:
    branches: [master, development]

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy

      - name: Install dependencies
        run: npm ci

      - name: Build TypeScript
        run: npm run build:design

      - name: Run TypeScript tests with coverage
        run: npm run test:design:coverage

      - name: Install cargo-tarpaulin for Rust coverage
        run: cargo install cargo-tarpaulin

      - name: Run Rust tests with coverage
        run: npm run test:coverage:rust

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/lcov.info,./coverage/cobertura.xml
          flags: unittests
          name: codecov-umbrella
