name: Dependencies

on:
  schedule:
    # Run weekly on Sundays at 2 AM UTC
    - cron: "0 2 * * 0"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update-rust-dependencies:
    name: Update Rust Dependencies
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      # Install LLVM 14 for dependency testing
      - name: Install LLVM 14
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            llvm-14 \
            llvm-14-dev \
            clang-14 \
            libclang-14-dev \
            libclang-common-14-dev
          echo "LLVM_SYS_140_PREFIX=/usr/lib/llvm-14" >> $GITHUB_ENV
          echo "LLVM_CONFIG_PATH=/usr/bin/llvm-config-14" >> $GITHUB_ENV
          echo "LIBCLANG_PATH=/usr/lib/llvm-14/lib" >> $GITHUB_ENV

      - name: Update Cargo dependencies
        run: cd compiler && cargo update

      - name: Run tests with updated dependencies
        run: |
          cd compiler && cargo test
          make test

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: update Rust dependencies"
          title: "Update Rust Dependencies"
          body: |
            Automated update of Rust dependencies.

            - Updated Cargo.lock with latest compatible versions
            - All tests pass with updated dependencies

          branch: update-rust-deps
          delete-branch: true

  update-npm-dependencies:
    name: Update npm Dependencies
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Update npm dependencies
        run: |
          npm update
          npm audit fix || true

      - name: Run tests with updated dependencies
        run: |
          npm run test:design
          make test-design

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: update npm dependencies"
          title: "Update npm Dependencies"
          body: |
            Automated update of npm dependencies.

            - Updated package-lock.json with latest compatible versions
            - Fixed security vulnerabilities with npm audit fix
            - All tests pass with updated dependencies

          branch: update-npm-deps
          delete-branch: true
